### ISSUE TITLE
JSON Serialization not recursive 

### ISSUE THREAD

**Issue by ublanke** [cph-cachet/research.package#46]
Hi everyone,

calling _.toJson()_ on a _RPTaskResult_, does not encode recursively children _RPStepResult_ into an expected JSON consisting of basic types, dictionaries or lists. 

`{identifier: surveyTaskID, start_date: 2021-08-09T10:27:49.529856, end_date: 2021-08-09T10:27:54.086450, results: {symptoms: **Instance of 'RPStepResult**'}}`

Or is this expected not to be recursive?

My workaround for now is to call subsequently jsonEncode-->String and jsonDecode--Map to receive a JSON-structure with basic types.

**Comment by MadsVSChristensen** [comment]
Hi ublanke, 
This is expected behavior. The json_serialization package uses `explicit_to_json: false` as default for recursive JSON serialization and so do we. It is our idea that its better to use the RPTaskResult object as an object for extraction any type of information you might want, and get a complete JSON string representation later whenever that is needed. 

I recommend using either of the two solutions below for a full json string conversion:
```dart 
json.encode(result);

JsonEncoder.withIndent(' ').convert(result);
```
Thank you for your question.

**Comment by ublanke** [comment]
Perfect, thank you so much for clarification and the suggestion. 
I still need to navigate the Flutter packages better ;).
